server:
  port: 8080
spring:
  application:
    name: dmp-evaluator-service
  # Jackson Configuration for JSON Processing
  jackson:
    serialization:
      indent_output: true  # Pretty-print JSON
    #default-property-inclusion: non_null  # Ignore null values
  data:
    mongodb:
      uri: mongodb://localhost:27017/dmp-evaluator

logging:
  level:
    root: info
    org.springframework: DEBUG
    io.github.ostrails.dmpevaluatorservice: DEBUG

dmp:
  global:
    repository: "https://github.com/OSTrails/DMP-Evaluation-Service"
    mitLicense: "https://opensource.org/license/mit"
    unpayWallEndPoint: "https://api.unpaywall.org/v2/"
    unpayWallEmail: "dmpEvalutionService@test.com"
    fairChampionEndPoint: "https://tests.ostrails.eu/assess/test/"
  test:
    endpointURL: "http://localhost:8080/tests"
  metric:
    endpointURL: "http://localhost:8080/metrics"
  benchmark:
    endpointURL: ${BENCHMARK_URL}

